### ISSUE TITLE
Can't use sortObjectKeys option

### ISSUE THREAD

**Issue by vamcs** [mariohmol/ang-jsoneditor#51]
When setting the option sortObjectKeys to true, an error is always thrown and the editor never loads.

```
ERROR TypeError: Cannot read property 'findNodeByInternalPath' of null
    at JSONEditor.push../node_modules/jsoneditor/src/js/treemode.js.treemode._onChange (treemode.js:475)
    at JSONEditor.push../node_modules/jsoneditor/src/js/treemode.js.treemode._onAction (treemode.js:453)
    at Node.push../node_modules/jsoneditor/src/js/Node.js.Node.sort (Node.js:3757)
    at Node.push../node_modules/jsoneditor/src/js/Node.js.Node.setValue (Node.js:491)
    at new Node (Node.js:37)
    at JSONEditor.push../node_modules/jsoneditor/src/js/treemode.js.treemode.set (treemode.js:180)
    at JSONEditor.push../node_modules/jsoneditor/src/js/JSONEditor.js.JSONEditor.setMode (JSONEditor.js:290)
    at JSONEditor.push../node_modules/jsoneditor/src/js/JSONEditor.js.JSONEditor._create (JSONEditor.js:199)
    at new JSONEditor (JSONEditor.js:149)
    at JsonEditorComponent.ngOnInit (ang-jsoneditor.js:68)
```

**Comment by mariohmol** [comment]
This seems to be something in jsoneditor.

I just released a version 1.8.2 , can u please install and do:

Use debug mode to see in your console the data and options passed to jsoneditor. Copy this and paste in your issue when reporting bugs.

```html
<json-editor [debug]="true" [options]="editorOptionsData" [data]="dataStructure"></json-editor>
```

**Comment by mariohmol** [comment]
The error seems to be in this line:

* https://github.com/josdejong/jsoneditor/blob/3f182a1f0411764fabab1d9bb35bbfbaaa41f67c/src/js/treemode.js#L474

But we need the console log with data + options to open a bug there.

**Comment by mariohmol** [comment]
hi.. there is a nw version with newest jsoneditor as well.. please retest and if this still an issue.. please reopen

**Comment by vamcs** [comment]
I've updated the Angular extension and jsoneditor, but I still get an error. I forgot to say that I'm using the editor in a reactive form, so passing I'm passing `formControlName` to it. The error is thrown right after the editor starts, even if I start it empty. The debug doesn't really give much useful information at this point, but I can see it crashes before all properties are loaded by the editor.

Versions:
- ang-jsoneditor: ^1.8.3
- jsoneditor: ^7.0.4

How I use the component:
```
<form fxFill [formGroup]="form">
    <json-editor 
        [debug]="true" 
        [options]="editorOptions" 
        formControlName="translations"></json-editor>
</form>
```

Now, the sorting works but only after the error is thrown. As said, the error occurs even if the editor is empty.
---

**First debug and error logs:**
![image](https://user-images.githubusercontent.com/18034802/67200846-20928d80-f405-11e9-8093-67b295f6c7f8.png)

**Second debug log (the data loaded is now a string instead of an object):**
![image](https://user-images.githubusercontent.com/18034802/67200892-3bfd9880-f405-11e9-895e-3975da5f4d41.png)

**Third debug log (after data loads from the backend. It doesn't make any different to add a NgIf to check if the data exists):**
![image](https://user-images.githubusercontent.com/18034802/67200951-66e7ec80-f405-11e9-9a2b-89a91cf38a32.png)

**The line where the problem occurs in ang-jsoneditor:**
![image](https://user-images.githubusercontent.com/18034802/67201004-8f6fe680-f405-11e9-991f-93f8f029fab3.png)

**Comment by mariohmol** [comment]
Running on local demo of this project works.. but indeed for stackblitz i have the same issue https://stackblitz.com/edit/ang-jsoneditor

this is now fixed on 1.8.4

thanks for that!
